### ISSUE TITLE
Bug: parsing of values with <>

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/autorender#105]
## inside a index.stache
```html
 <meta name="author" content="DIREKTSPEED <frank@dspeed.eu>"> 
```

will render wrong as 
```html
 <meta name="author" content="DIREKTSPEED <frank@dspeed.eu> 
```

i don't include more debug info as this is probally existing in all versions it should be at last as i got such errors more often but never found the reason befor.

**Comment by justinbmeyer** [comment]
We can use `can-parse` to fix this.

**Comment by frank-dspeed** [comment]
@justinbmeyer i hope that you don't mean i should replace with something like

```js
parser("<my-element bar='car'/>" ,function(token, expressions){
	token //-> { lex: "<", match: "<", index: 0 }
	expressions.end // -> []
	expressions.start
	// ->[
	// 	{
	//		"expression": "EXPRESSION",
	//		"ruleIndexes": [ 0, 3 ]
	// 	},
	// 	{
	//		"expression": "TAG",
	//		"ruleIndexes": [ 0, 1, 2, 3, 4, 5]
	// 	}
	// ]
});
```

**Comment by chasenlehara** [comment]
He’s saying that we can fix this issue within done-autorender by switching to can-parse, not that you need to implement it yourself. 😊

**Comment by matthewp** [comment]
done-autorender doesn't do parsing, that's done in can-stache. Going to move the issue there.

**Comment by bmomberger-bitovi** [comment]
https://github.com/canjs/can-view-parser/pull/84 should fix that -- it's deployed in the latest can-stache so upgrading the can-stache dependency in your app should fix that.

**Comment by frank-dspeed** [comment]
Verifyed closed by: https://github.com/canjs/can-view-parser/pull/84
