### ISSUE TITLE
Major: depends on deprecate can-util modules

### ISSUE THREAD

**Issue by matthewp** [donejs/autorender#122]
This depends on can-util/dom/mutate/mutate which we can't use in canjs 4.0. I need to update the usage to get rid of can-util if possible.

**Comment by m-mujica** [comment]
Probably you noticed this already, but just in case, we need to change this line 

https://github.com/donejs/autorender/blob/e84055866aa197e18735680860372945c79d724c/test/unit.js#L22

Unlike Mocha, QUnit won't fail if `done` is passed an argument. I also found that if you do this:

```js
.then(done, function(e) {
  assert.notOk(e, "there should be no error");
  done();
});
```

The setup hook will fail BUT it will run the `QUnit.test`s anyway. So I guess this is the way to go, if the `setup` fails don't run assertions.

```js
.then(done, function(e) {
  assert.notOk(e, "there should be no error");
});
```

**Comment by matthewp** [comment]
https://github.com/donejs/autorender/pull/123
