### ISSUE TITLE
Tests are breaking in master branch

### ISSUE THREAD

**Issue by mjstahl** [donejs/autorender#139]
_The new ViewModel is bound to the route_  tests are breaking when run from the console and from the `test.html` page.

When that module is run in isolation, all three tests pass.

<img width="601" alt="screen shot 2018-03-16 at 10 58 41" src="https://user-images.githubusercontent.com/212726/37527944-a81b4986-2909-11e8-94de-b3a07c0befad.png">

**Comment by matthewp** [comment]
Closed by https://github.com/donejs/autorender/pull/184
