### ISSUE TITLE
Error in releases > 2.5.1

### ISSUE THREAD

**Issue by leoj3n** [donejs/autorender#209]
The version `2.5.1` release was working fine until I updated to `2.5.5`, then I got this devtools error:

![image](https://user-images.githubusercontent.com/990216/50458183-d779c600-0926-11e9-9ee8-28642ba00501.png)

Firefox shows a slightly different error in devtools console:

![image](https://user-images.githubusercontent.com/990216/50458250-3f301100-0927-11e9-9caf-a790acc71ec6.png)

The page that errors has a stache loop `{{#for (item of items)}}`. That loop stops printing any items in both browsers with an error in console. The home page still loads fine (that stache is without loops).

I tried version `2.5.2` which crashed the app while `2.5.3` and `2.5.4` did not show any errors in console but still no items printed on the page with the loop in stache.

I'll be sticking to `2.5.1` for now. Let me know if you have any ideas of what you want me to try.

**Comment by matthewp** [comment]
Thanks for reporting. Releases after 2.5.1 were meant to bring support for the `{{#portal()}}` helper to done-autorender based apps. It was a big-ish change.  I would like to fix this as soon at possible.

Does this error happen in your terminal in a donejs app or in the browser console?

**Comment by matthewp** [comment]
@leoj3n would you might upgrading to the latest and see if you still get it? I changed how this stuff works a bit.

**Comment by leoj3n** [comment]
Tested and working with can@5.21.4

**Comment by matthewp** [comment]
Awesome.
