### ISSUE TITLE
Configure when rendering occurs

### ISSUE THREAD

**Issue by akagomez** [donejs/autorender#27]
`done-autorender` currently defaults to rendering the `main` template after all asynchronous actions have resolved. This is a suitable default in the context of DoneJS because SSR has presented a resolved/static application in the meantime, but outside the context of DoneJS this default undermines progressive loading features that are developed into the app (for the initial page load).

**Comment by matthewp** [comment]
Yeah I agree, done-autorender should be generally useful but the default here makes it sort of unuseful without done-ssr.

**Comment by justinbmeyer** [comment]
@matthewp we probably need two different modules so clients don't have to load `can-zone` unnecessarily.  Unfortunately, we already have `can-autorender`.  What do you think the best solution is?

**Comment by matthewp** [comment]
There could be a `done-autorender/no-zone` (bad name). No need to create a new package I don't think.

**Comment by matthewp** [comment]
Marking this as DoneJS 1.1 for now.

**Comment by matthewp** [comment]
This was fixed by #68
