### ISSUE TITLE
In autorender template, set canRoute.data directly instead of calling canRoute.map

### ISSUE THREAD

**Issue by mjstahl** [donejs/autorender#31]
Per the warning from https://github.com/canjs/can-route/blob/master/can-route.js#L542 set the canRoute.data directly in the autorender template.

**Comment by pYr0x** [comment]
I think this is done by the or from @bajix https://github.com/donejs/autorender/commit/23e7ad4f529c4b1b94f1ceb07ec36905263ab2b6#diff-5aaa80b08854707dd6d2ca8360926359
