### ISSUE TITLE
Renderer zone never completes

### ISSUE THREAD

**Issue by bgando** [donejs/autorender#86]
How to re-create:

Clone these repos and run them: 
https://github.com/bitovi/tribe-radiance
https://github.com/bitovi/tribe-radiance-api

Remove no-zone flag from package.json
Sign up for the app (to create a user)
Log into the app
Refresh the app, if the jwt token is there, there will be an issue with this.displayPage in the app.js VM

**Comment by justinbmeyer** [comment]
- https://github.com/canjs/can-connect-feathers/blob/master/session/session.js#L91

**Comment by matthewp** [comment]
@bgando I'm not able to sign up for the app. When I try to signup I get an error related to this code:

```js
  meditator: {
    Type: Meditator,
    value() { return this.meditators[0] }
  },
```

`this.meditators` doesn't exist on the viewmodel. Am I doing something wrong?

**Comment by matthewp** [comment]
@bgando ^^

**Comment by matthewp** [comment]
Going to close.
